### ISSUE TITLE
[Bug] roslaunch master_simulation rvo_turtlebot_gazebo.launch

### ISSUE THREAD

**Issue by guduzhe123** [hanruihua/master_multirobot#1]
Hi, this is a very great project. Thank you for sharing.

By the way, I come across a problem when I start the gazebo simulation. When I start "roslaunch master_simulation rvo_turtlebot_gazebo.launch" and the result:

unused args [ROBOT_INITIAL_POSE, model] for include of [/opt/ros/kinetic/share/turtlebot_gazebo/launch/includes/kobuki.launch.xml]

Can you tell me how to solve this problem. Thanks a lot.

**Comment by hanruihua** [comment]
Hi, thank you for paying your attention to my project. I am sorry for that I see this message so late
The reason for this problem is that the file kobuki.launch.xml has the default value of the initial pose and model name set by the environment variable.  You should change this value using the argument syntax in the launch file.  The example file is attached. 
[kobuki.txt](https://github.com/hanruihua/master_multirobot/files/4400613/kobuki.txt)
